name = "mar-de-java"
compatibility_date = "2026-06-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "mar-java-db"
database_id = "63d3785c-851f-4793-9b86-9dc205f32d43"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "R2"
bucket_name = "mar-java-showroom"
